### ISSUE TITLE
Error in sha256() implementation

### ISSUE THREAD

**Issue by Egor-Skriptunoff** [fuxoft/krypta#1]
This assertion fails:

``` lua
assert(sha256(("a"):rep(55)) ==
"9f4390f8d30c2dd92ec9f095b65e2b9ae9b0a925a5258e241c9f1e910f734318")
```

The error is in the implementation of preprocess256() function.
Calculating of "padding" is wrong when `#input % 64 == 55`
This can be fixed by replacing

``` lua
   local padding = 64 - ((length + 9) % 64);
```

with

``` lua
   local padding = (-length-9) % 64
```

Probably, this fix does not have any importance for your particular usage of sha256(), but it may be very important for people (like I am) who are searching for effective LuaJIT code for calculating genuine SHA256.

---

BTW, there is one little performance improvement available:
You are creating a new GC-collectable object (string in variable "chunk") for every 64 bytes of input.
This could be avoided by removing variable "chunk" and replacing

``` lua
   num = bor(num, string.byte(chunk:sub(i+j, i+j)))
```

with

``` lua
   num = bor(num, string.byte(input, t-1+i+j))
```

**Comment by fuxoft** [comment]
Thank you, I will have a look at it next week, after I return from the vacation.

On 9/6/16, Egor-Skriptunoff notifications@github.com wrote:

> This assertion fails:
> 
> ``` lua
> assert(sha256(("a"):rep(55)) ==
> "9f4390f8d30c2dd92ec9f095b65e2b9ae9b0a925a5258e241c9f1e910f734318")
> ```
> 
> The error is in the implementation of preprocess256() function.
> Calculating of "padding" is wrong when `#input % 64 == 55`
> This can be fixed by replacing
> 
> ``` lua
>    local padding = 64 - ((length + 9) % 64);
> ```
> 
> with
> 
> ``` lua
>    local padding = (-length-9) % 64
> ```
> 
> Probably, this fix does not have any importance for your particular usage of
> sha256(), but it may be very important for people (like I am) who are
> searching for effective LuaJIT code for calculating genuine SHA256.
> 
> ---
> 
> BTW, there is one little performance improvement:
> You are creating a new GC-collectable object (string in variable "chunk")
> for every 64 bytes of input.
> This could be avoided by removing variable "chunk" and replacing
> 
> ``` lua
>    num = bor(num, string.byte(chunk:sub(i+j, i+j)))
> ```
> 
> with
> 
> ``` lua
>    num = bor(num, string.byte(input, t-1+i+j))
> ```
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/fuxoft/krypta/issues/1

## 

_-- Frantisek Fuka_
(yes, that IS my real name)

-- My Personal homepage: www.fuxoft.cz
-- My Google+ profile: google.com/+fuxoft
-- My Telegram chat: telegram.fuxoft.cz
